name: titandb-dev
channels:
  - conda-forge
  - defaults
  - titan-search
dependencies:
  - gcc
  - gxx
  - sysroot_linux-64=2.17 # [linux]
  - turbo
  - titan-rocksdb
  - gtest
  - gmock
  - benchmark
